apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradingpost-deployment
  labels:
    app: tradingpost-errbot
spec:
  selector:
    matchLabels:
      app: tradingpost-errbot
  template:
    metadata:
      labels:
        app: tradingpost-errbot
    spec:
      containers:
      - name: tradingpost-errbot
        image: ghcr.io/torgeirl/tradingpost-errbot:latest
        env:
          - name: ERRBOT-TOKEN
            valueFrom:
              secretKeyRef:
                name: tradingpost-config 
                key: errbot-token
          - name: ERRBOT-ADMINS
            valueFrom:
              secretKeyRef:
                name: tradingpost-config
                key: errbot-admins
