apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradingpost-deployment
  labels:
    app: tradingpost-errbot
spec:
  template:
    metadata:
      labels:
        app: tradingpost-errbot
    spec:
      containers:
      - name: tradingpost-errbot
        image: docker.pkg.github.com/torgeirl/tradingpost-errbot/image:latest
